Add Greeting for New Players
hackclub/HCCore pull request #88
Opened 2020-04-30 20:27 UTC by jasonappah

If you run /tutorial you'll get this: 

![tutorial](https://user-images.githubusercontent.com/30608521/80755712-ebbf6b80-8af6-11ea-8632-759714c5da80.png)

New players will also get that when they join.

Closes #86.

2020-04-30 20:53 UTC, jasonappah commented
Btw the code is kinda jank but it works, so if anyone has suggestions of what to edit, I can definitely try to fix it.

2020-04-30 22:52 UTC, ifvictr commented on src/main/java/com/hackclub/hccore/listeners/PlayerListener.java
> +
Can you fix the indentation here?

2020-04-30 22:52 UTC, ifvictr commented on src/main/java/com/hackclub/hccore/listeners/PlayerListener.java
> +        if (event.getPlayer().hasPlayedBefore() == false) {
This can be simplified to `!event.getPlayer().hasPlayedBefore()`

2020-04-30 22:54 UTC, ifvictr commented on src/main/java/com/hackclub/hccore/commands/TutorialCommand.java
> +    private static final String[] message = {ChatColor.RED + "Greetings! Welcome to the Hack Club vanilla Minecraft server!", "You can use /nick to set your nick name and /color to set your chat and
Can you use the Java code linter? It'll automatically split it into multiple lines.

2020-04-30 22:54 UTC, ifvictr commented on src/main/java/com/hackclub/hccore/commands/TutorialCommand.java
> +            }
Indentation

2020-04-30 22:55 UTC, ifvictr commented on src/main/java/com/hackclub/hccore/commands/TutorialCommand.java
> +    private static final String[] message = {ChatColor.RED + "Greetings! Welcome to the Hack Club vanilla Minecraft server!", "You can use /nick to set your nick name and /color to set your chat and
This is a static variable—its name should be fully uppercased.

2020-04-30 22:55 UTC, ifvictr commented on src/main/java/com/hackclub/hccore/commands/TutorialCommand.java
> +        for (String i : TutorialCommand.message) {
Change variable name `i` to `message`

2020-04-30 22:56 UTC, ifvictr commented on src/main/resources/plugin.yml
> +
Remove the extra new line at the end

2020-04-30 22:59 UTC, ifvictr commented on src/main/java/com/hackclub/hccore/listeners/PlayerListener.java
> +            event.getPlayer().performCommand("tutorial");
You should make a function called `startTutorialFlow` that takes a player as the parameter. This feels a little hacky lol.

2020-05-02 22:06 UTC, nice6599 commented on src/main/java/com/hackclub/hccore/commands/TutorialCommand.java
> +        Player player = (Player) sender;
player variable is unused.

2020-05-02 22:11 UTC, nice6599 commented on src/main/java/com/hackclub/hccore/commands/TutorialCommand.java
> +        }
i would consider staying consistent with the rest of the commands and using a if else statement
#### Example:
``` java
if (sender instanceof Player) {
                sender.sendMessage("message");
            } else {
                sender.sendMessage(ChatColor.RED + "You must be a player to use this");
            }
            return true;
```

2020-05-02 22:15 UTC, nice6599 commented on src/main/java/com/hackclub/hccore/commands/TutorialCommand.java
> +    private static final String[] message = {ChatColor.RED + "Greetings! Welcome to the Hack Club vanilla Minecraft server!", "You can use /nick to set your nick name and /color to set your chat and
I suggest that you include the "greeting" part in a new player event so "greeting" does not message when you run the command again.

2020-05-02 22:15 UTC, nice6599 commented on src/main/resources/plugin.yml
> +    description: Greets new users to the server
fix description. the command itself does not greet new users. 

> I suggest that you include the "greeting" part in a new player event so "greeting" does not message when you run the command again.

2020-11-09 22:54 UTC, zanedb commented
Honestly, I'm not sure text is the best way to introduce the rules. I think a lot of players will ignore or skim over it, especially when joining. I've seen a few servers do a floating item frame walkway that introduces the rules at their spawn, which I quite like:

![image](https://user-images.githubusercontent.com/16865690/98605023-a051fb00-2299-11eb-81ba-d195b6323020.png)

If we're building a new spawn area (which @eankeen & I have talked about), perhaps we could do something similar to the above in that area. Then, maybe this command could become `/info` (so you don't have to go to spawn to see the rules). What do y'all think?

2020-11-10 03:02 UTC, eankeen commented
yeah not just having raw text would look much nicer

2020-11-10 04:24 UTC, jasonappah commented
Omg I totally forgot about this PR! I do like the item frame idea a lot
more though

On Mon, Nov 9, 2020 at 9:03 PM Edwin Kofler <notifications@github.com>
wrote:

> yeah not just having raw text would look much nicer
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/HCCore/pull/88#issuecomment-724418888>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHJQZCO26DL33WEABQD22STSPCUOXANCNFSM4MWSU2IQ>
> .
>

2021-07-06 02:16 UTC, alx-alexpark requested changes

2021-07-06 02:16 UTC, alx-alexpark commented on src/main/java/com/hackclub/hccore/commands/TutorialCommand.java
> +    private static final String[] MESSAGE = {ChatColor.RED + "Greetings! Welcome to the Hack Club vanilla Minecraft server!", "You can use /nick to set your nick name and /color to set your chat and
```suggestion
    private static final String[] MESSAGE = {ChatColor.RED + "Greetings! Welcome to the Hack Club vanilla Minecraft server!", "You can use /nick to set your nick name and /color to set your chat and name colors", ChatColor.RED + "Rules:", "Be nice.",  "No griefing or stealing", "No mods that give an unfair advantage", "Follow Hackclub CoC", "If you want to contribute to plugin development head on over to the GitHub: " + ChatColor.RED + "https://github.com/hackclub/HCCore/. ", "Type /tutorial to see this at any time and /discord to join the Discord!" + ChatColor.BLUE + ChatColor.BOLD + "Also checkout the modded server!"};
```

2021-07-06 02:16 UTC, alx-alexpark commented on src/main/java/com/hackclub/hccore/commands/TutorialCommand.java
> +    private static final String[] MESSAGE = {ChatColor.RED + "Greetings! Welcome to the Hack Club vanilla Minecraft server!", "You can use /nick to set your nick name and /color to set your chat and
Update welcome message a bit

2021-07-06 02:17 UTC, alx-alexpark commented on src/main/java/com/hackclub/hccore/commands/TutorialCommand.java
> +    private static final String[] MESSAGE = {ChatColor.RED + "Greetings! Welcome to the Hack Club vanilla Minecraft server!", "You can use /nick to set your nick name and /color to set your chat and
Once these changes are accepted im happy to approve and merge :)

2021-07-14 20:19 UTC, jasonappah commented
I think this PR is GTG, just need to run linting rq

2021-07-14 21:32 UTC, alx-alexpark reviewed
Looks good, just don't forget to mention the modded server, its important so put it in **bold**, thanks :) after that i'l merge

2021-07-14 21:53 UTC, jasonappah commented
Correct me if I'm wrong but I already have it bolded

2024-09-10 22:09 UTC, closed without merging

2024-09-18 01:49 UTC, Monoverde888 commented
why was this closed?

2024-09-18 03:00 UTC, polypixeldev commented
> why was this closed?

old pr that would've needed a lot of time spent to make work with new code - but if you @Monoverde888 would like to try to get this pr in a working state feel free!